v2.0.0
01org/intel-iot-services-orchestration-layer pull request #38
Opened 2016-09-30 10:04 UTC by AndrewSoul

mysql模块
     所有具体功能模块用户都要输入:1、host（mysql数据库的host） 2、port（mysql数据库的port） 3、database(用户输入数据库) 4、user(数据库名) 5、password (数据库密码) 
     Notice:使用该模块前要先安装node-mysql模块。因为每个模块中require了mysql。

具体模块:
一、mysql_create table： mysql建数据表。
    输入：table（用户需要新建的数据表）  
    输出：result
    具体使用：只需要用户输入具体建表所需要的语句。例如用户想新建个数据表student，只需要在table               输入栏输入student即可。
            
二、mysql_drop table:   mysql删除数据表。
       输入：table(用户要删除的表名)
       输出：result
       具体使用：只需要用户输入要删除的数据表即可。例如：删除数据表student，用户在table输入栏输入student，结果查看result。

三、mysql_insert :  mysql插入数据。
        输入：1、table(数据所插入的表)   2、values（所插入的数据）
        输出：result
       具体使用：例如，在student数据表中插入记录name=’abc’。
用户在table输入栏输入student，在values输入栏输入name=’abc’。        

四、mysql_delete: mysql删除数据。
       输入：1、table(所要删除的表名)。 2、condition(删除所在记录的条件)
       输出：result
       具体使用：例如，要删除student表里name=’Bob’的记录。用户在table输入栏输入student,在condition输入栏输入name=’Bob’。

五、mysql_query:mysql查询数据。
       输入：1、field（所要查询的数据项）。 2、table（所要查询的表名）。 3、condition(查询条件) 
      输出：result
      具体使用：例如，要查询student表里name=’Bob’所在记录的所有信息。
用户在field输入栏输入*，在table输入栏输入student，在condition输入栏输入name=’Bob’。结果即可在调试页面的result中查看。
  
六、mysql_update:mysql更新数据。
         输入：1、table(用户所要更新数据所在的表名)。 2、item（用户所要更新的数据）。 
         3、condition(用户所要更新数据的条件)
         输出：result
         具体使用：例如，要更新student表里name=’Bob’的那一项，把id更新为10。用  户在table输入栏输入student，在item输入栏输入id=10，在condition输入栏输入name=’Bob’。结果即可在调试页面的result中查看。

2016-10-04 05:48 UTC, jiangzidong requested changes

2016-10-04 05:48 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mysql/create table/i18n.zh-CN.json
> +}
文件请以"回车符"结尾, 下同

2016-10-04 05:48 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mysql/create table/kernel.js
> +	host:IN.host,
请不要用tab符, 缩进统一用2个space

2016-10-04 05:48 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mysql/create table/start.js
> +done();
只要done()的文件是不需要的, 如果该文件缺失, 系统会创建默认start.js, 而默认的内容就是done()

2016-10-04 05:52 UTC, jiangzidong commented
* 如果内置模块需要依赖npm库, 请添加在center/package.json中

* 使用该module还需要什么准备工作, 比如mysql的安装?

* commit message请具体一点, 而不是"v2.0.0"

Thanks

2016-10-05 06:55 UTC, closed without merging

2016-10-05 08:48 UTC, jiangzidong commented
@AndrewSoul 你是新开了一个PR是吗? 以后就直接git commit --amend 修改, 然后git push -f 覆盖即可

2016-10-05 11:59 UTC, AndrewSoul commented
嗯嗯，好的。  我是新开了一个PR。