Dev -Add mysql related service as builtin service
01org/intel-iot-services-orchestration-layer pull request #41
Opened 2016-10-04 15:14 UTC by AndrewSoul

Add mysql related service as builtin service based on node-mysql. It needs requiring mysql module. 
To use this service, you need to install mysql on your computer and set mysql configuration properly. Because every service needs mysql related information,such as host,port,mysql username,mysql password,mysql database.

2016-10-09 01:32 UTC, liang-jie commented
首先,我觉得写的还是很不错的~但是我说一下个人看法~
1.创建数据表,增删改查等操作每个都是一个service,但是像条件等语句还是需要用户输入的,而且像在插入时很多复杂的语句也没有办法兼容,是否可以考虑将所有srevice合并为一个servcie,输入是sql语句.因为之前的很多条件还是需要用户写语句的,需要用户对sql语句有基本了解.
2.start.js里面的语句只有在启动时会执行一次,数据库连接可以考虑放到这个里面去,stop.js中可以考虑放入数据库连接的关闭,在发生错误时,建议使用sendERR.这样代码更规范,使用和调试时也更方便.

2016-10-09 02:00 UTC, jiangzidong commented
@AndrewSoul 还有一点, 请将这4个commit做一些合并, 可以4个合并为1个, 或者	add mysql dependency 和 	add mysql related service as builtin service 合并, 中间两个合并. 因为一般来说, checkout到每一个commit, 都应该能正常运行.

2016-10-09 11:52 UTC, AndrewSoul commented
你好，那我能重新PR吗？因为改动可能比较大. @jiangzidong   @liang-jie

2016-10-10 04:53 UTC, jiangzidong commented
@AndrewSoul 不建议重新PR
你可以先把当前两个commit合并, 然后git commit --amend修改, 最后git push -f 强制push到你的dev branch 就可以了

2016-10-10 16:49 UTC, AndrewSoul commented
请问现在的修改可以吗？ 这里说文件冲突,我把PR的package.json更新过了。

2016-10-11 00:35 UTC, jiangzidong commented
请rebase到最新的dev branch

2016-10-11 07:45 UTC, AndrewSoul commented
已更新。请问还有什么需要修改的吗？
@liang-jie @jiangzidong

2016-10-11 07:49 UTC, jiangzidong requested changes

2016-10-11 07:49 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mysql/mysql_service/service.json
> +		"required":true
缩进格式, 下面的require都请修改一下

2016-10-11 07:49 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mysql/mysql_service/stop.js
> +done();
回车符结束

2016-10-11 07:49 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mysql/mysql_service/kernel.js
> +
回车符结束

2016-10-11 07:57 UTC, AndrewSoul commented on center/lib/hubbundles/thingbundle/mysql/mysql_service/service.json
> +		"required":true
好的，commit上去就乱了。。现在改。

2016-10-11 08:00 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mysql/mysql_service/service.json
> +		"required":true
因为你用tab了, 这里tab长度和你本地editor不一样.
这也就是为什么不要用tab的原因

2016-10-11 08:00 UTC, jiangzidong requested changes

2016-10-11 08:00 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mysql/mysql_service/kernel.js
> +	  console.log(err);
tab

2016-10-11 08:00 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mysql/mysql_service/kernel.js
> +	  sendOUT({result:result});
tab

2016-10-11 08:00 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mysql/mysql_service/kernel.js
> +	sendOUT({err:err});
tab

2016-10-11 08:13 UTC, AndrewSoul commented on center/lib/hubbundles/thingbundle/mysql/mysql_service/service.json
> +		"required":true
哦哦。  谢谢提醒。  能否再麻烦check一下

2016-10-11 08:15 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mysql/mysql_service/service.json
> +	"required":true
还是tab...

2016-10-11 08:28 UTC, AndrewSoul commented on center/lib/hubbundles/thingbundle/mysql/mysql_service/stop.js
> +done();
是回车结束的呀

2016-10-11 08:31 UTC, AndrewSoul commented on center/lib/hubbundles/thingbundle/mysql/mysql_service/service.json
> +	"required":true
真抱歉啊。。我看了下，应该是没有缩进问题了。

2016-10-11 08:33 UTC, jiangzidong approved these changes

2016-10-11 08:55 UTC, jiangzidong requested changes

2016-10-11 08:55 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mysql/mysql_service/service.json
> +    "id":"__HOPE__/builtin/mysql_service",
__HOPE__/builtin/mysql/mysql_service
这样比较好, 包括了thingname 和 servicename

2016-10-11 08:55 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mysql/mysql_service/service.json
> +    ],
多了"逗号", 错误的json格式 你的环境下这样可以正常运行吗?

2016-10-11 08:55 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mysql/mysql_service/kernel.js
> +
你sendout用了3个port: err s 和 result
而你在service.json中注册时port叫做"value"

你如果将这个service放入工作流, 他是不可用的,因为outport将没有输出 
请统一这些命名
sendOUT({err:err}); 可以改为sendERR(err)

2016-10-11 08:55 UTC, jiangzidong commented on doc/md/builtin/mysql_service.md
> +`out` : result.
这里outport名字也请统一, 包括下面图片部分

如果你看center.log, 是会看到报错信息的, 找不到s, result 这样的outport

2016-10-11 09:09 UTC, AndrewSoul commented on doc/md/builtin/mysql_service.md
> +`out` : result.
好的。马上修改。 麻烦你了。

2016-10-11 09:40 UTC, AndrewSoul commented on center/lib/hubbundles/thingbundle/mysql/mysql_service/kernel.js
> +
图片清晰度可以吗？  另外示例是嵌套查询还是简单的demo就行。

2016-10-11 12:05 UTC, AndrewSoul commented
New One~Please check again.

2016-10-11 12:22 UTC, jiangzidong approved these changes

2016-10-11 12:24 UTC, jiangzidong commented
LGTM

2016-10-12 01:17 UTC, liang-jie commented
LGTM

2016-10-12 01:19 UTC, merged

2016-10-20 02:44 UTC, jiangzidong commented
hi @AndrewSoul 
现在的ISOL支持一键发布的的service到云端
对应的, 也支持一键下载安装所需要的service
http://01org.github.io/intel-iot-services-orchestration-layer/#getstarted/example/publish_service

我们建议你发布这个service, 使更多的人可以使用它:)
(以后ISOL可能会目录调整, 精简builtin service的数量)

2016-10-20 07:46 UTC, AndrewSoul commented
好的，我会尽快发布的。