新增图片压缩服务
01org/intel-iot-services-orchestration-layer pull request #45
Opened 2016-10-09 02:41 UTC by helianthuswhite

## 新增图片压缩服务

### 输入参数：

_inputPath_: 源图片绝对路径

_width_: 目的图片的宽度

_height_: 目的图片的高度

_outputPath_: 目的图片的绝对路径

### 输出结果：

_isSuccess_: true or false

是否压缩成功

通过node添加图片压缩服务，能够在本地快速改变图片大小和图片的像素，以此来减少一些对图片进行云处理（比如图片的识别等）的时间。

2016-10-09 02:43 UTC, jiangzidong requested changes

2016-10-09 02:43 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/compression/ImageCompression/kernel.js
> +	inputPath: IN.inputPath,
缩进格式

2016-10-09 02:43 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/compression/ImageCompression/service.json
> +  "doc" : "builtin/compression.html#ImageCompression"
doc的内容能否一并提交

2016-10-09 02:45 UTC, helianthuswhite commented on center/lib/hubbundles/thingbundle/compression/ImageCompression/service.json
> +  "doc" : "builtin/compression.html#ImageCompression"
好的

2016-10-09 02:51 UTC, sunpeng1996 commented on center/lib/hubbundles/thingbundle/compression/ImageCompression/service.json
> +  "doc" : "builtin/compression.html#ImageCompression"
ok，马上。

2016-10-09 04:34 UTC, helianthuswhite commented
您好，我们的修改已经完成，请看一下是否还有其他的问题？

2016-10-10 01:30 UTC, jiangzidong requested changes

2016-10-10 01:30 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/compression/ImageCompression/service.json
> +		    {
缩进位置

2016-10-10 01:30 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/compression/ImageCompression/kernel.js
> +	  if(err) {
缩进位置
请不要用tab

2016-10-10 01:30 UTC, jiangzidong commented
请将这些commit合并为一个

2016-10-10 01:55 UTC, sunpeng1996 commented on center/lib/hubbundles/thingbundle/compression/ImageCompression/kernel.js
> +	  if(err) {
ok， thanks

2016-10-10 04:01 UTC, helianthuswhite commented
修改完成

2016-10-10 04:27 UTC, jiangzidong commented
@helianthuswhite  我们的doc是用md写的, 然后在build时生成html. 所以需要你再提供md文件
doc/md/builtin 下有很多例子
Thanks

2016-10-10 04:40 UTC, helianthuswhite commented
markdown文档添加完成

2016-10-10 04:49 UTC, jjykh commented
LGTM

2016-10-10 05:04 UTC, jiangzidong approved these changes

2016-10-10 05:14 UTC, jiangzidong commented
LGTM

2016-10-10 05:14 UTC, merged

2016-10-10 05:22 UTC, sunpeng1996 commented
您好，再打扰您一下，我想问，如果我们想增加的内置服务里面是调用其他脚本（比如python脚本，利用开启子进程的方式），换句话说，不是纯原生态node.js服务，是不是就不可以发merge request了？谢谢。期待您的回复，have a nice day!。 @jiangzidong

2016-10-10 05:46 UTC, jiangzidong commented
@sunpeng1996 也可以PR, 关键还是看具体解决了什么问题. 你用子进程的方法, 是因为这个功能只能python完成, 不能nodejs原生完成吗?

2016-10-10 05:54 UTC, sunpeng1996 commented
恩，是的，我们在本地增加了许多服务，子进程的使用大多数是因为这个功能没有node版本，或者找不到处理速度更快的node版本，我们会尽力完善改进我们的service，及时PR，谢谢您的答复。

2016-10-20 02:43 UTC, jiangzidong commented
hi @sunpeng1996 
现在的ISOL支持一键发布的的service到云端
对应的, 也支持一键下载安装所需要的service
http://01org.github.io/intel-iot-services-orchestration-layer/#getstarted/example/publish_service


我们建议你发布这个service, 使更多的人可以使用它:)
(以后ISOL可能会目录调整, 精简builtin service的数量)

2016-10-20 02:49 UTC, sunpeng1996 commented
好的。:)