添加二维码图片服务
01org/intel-iot-services-orchestration-layer pull request #49
Opened 2016-10-25 21:12 UTC by qq332769043

## 二维码图片
### 配置

`outputFolder`: 字符串类型。 你想输出二维码图片文件的目录，如果目录不存在则会被自动创建。

`fileName`: 字符串类型。 二维码图片文件的名字。

`type`: 字符串类型。二维码图片文件的格式，可选的值为：`png`(默认), `svg`, `eps` 和 `pdf`。

`size`: 整数类型。 一个二维码图片模块的像素大小.对于png和svg的默认值为5。但是这个配置对eps和pdf没有作用。

### 输入

`text`: 字符串类型。 你想转化成二维码图片文件的文本内容。

### 输出

`status`: 布尔类型. 输出二维码图片文件的状态信号. 如果是true, 那么服务就已经完成此次操作。

### 此服务通过qr-image将输入的文本生成二维码图片文件，可以用于IoT SOL的Image Widget显示，也可以用于服务器图片输出流。

2016-10-26 06:37 UTC, jiangzidong requested changes

2016-10-26 06:37 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/util/qrcode/kernel.js
> +	sendOUT({
不要用tab
所有缩进都是2个空格

2016-10-26 06:37 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/util/qrcode/start.js
> +done();
以回车结尾

2016-10-26 06:37 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/util/qrcode/kernel.js
> +	sendOUT({
其他文件要一样

2016-10-26 06:37 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/util/qrcode/service.json
> +	"default":"png"
没有对齐

2016-10-26 06:37 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/util/qrcode/service.json
> +	"required":true,
对齐

2016-10-26 06:39 UTC, jiangzidong commented
除了格式以外, 有一个建议
现在模块的输出是status
请增加一个输出: 图片路径

这样该模块放入工作流会更方便, 比如将该图片进行后续处理之类的

2016-10-26 08:10 UTC, qq332769043 commented
好的

2016-10-26 14:57 UTC, qq332769043 commented
@jiangzidong 我已经做出了这些更改但是我在本地合并了这些commit然后git push --force强制推送，所以这里可能没有满足Changes requested.

2016-10-27 01:17 UTC, jiangzidong approved these changes

2016-10-27 01:19 UTC, jiangzidong commented
LGTM, what do you think? @jjykh

2016-10-27 01:24 UTC, jjykh commented
LGTM

2016-10-27 01:27 UTC, jiangzidong commented
hi @qq332769043 我们会merge你的PR 谢谢
 
现在的ISOL支持一键发布的的service到云端
对应的, 也支持一键下载安装所需要的service
http://01org.github.io/intel-iot-services-orchestration-layer/#getstarted/example/publish_service

我们建议你发布这个service, 使更多的人可以使用它:)
(以后ISOL可能会目录调整, 精简builtin service的数量)

2016-10-27 01:27 UTC, merged