添加文件发送服务
01org/intel-iot-services-orchestration-layer pull request #50
Opened 2016-10-26 11:27 UTC by helianthuswhite

# 文件发送
该服务功能为发送文件到一个远程服务器，可以作为云服务API的使用或者与其他服务器之间进行文件通信。

## 输入参数
`url`:带有http:或者https:的远程服务器地址，如：http://127.0.0.1/ 或者 https://baidu.com/
`port`:远程服务器的端口，如果不填写的话http协议默认端口是80，https协议的默认端口是443
`filepath`:需要发送的文件的绝对路径
`keys`:该选项作为云服务API时需要填写的key值，如使用微软人脸识别服务需要填写在官网申请的API的识别码，填写方式：“Ocp-Apim-Subscription-Key:your-key”，若不需要key值验证则该项可以为空。

## 输出结果
`resdata`:将远程服务器返回的结果以字符串的形式输出。

## 样例图片
![image](https://cloud.githubusercontent.com/assets/12878076/19724277/eafabd0e-9bb1-11e6-9750-34238659f534.png)

![image](https://cloud.githubusercontent.com/assets/12878076/19724296/16e67462-9bb2-11e6-84db-c315ccfbfb0d.png)

![image](https://cloud.githubusercontent.com/assets/12878076/19724315/26937266-9bb2-11e6-8c64-1a419b0e0284.png)

2016-10-26 13:08 UTC, sunpeng1996 commented
LGTM

2016-10-27 01:30 UTC, jiangzidong commented
* 一般该模块在工作流中是如何使用的? 毕竟4个输入, 你们有典型应用场景吗? (部分输入可以作为config项)
* 这是一个通用的功能, 但是参数又比较复杂, 我个人建议可以将它改为某种特定的功能, 比如只是针对微软人脸识别服务的.

2016-10-27 01:46 UTC, helianthuswhite commented
我们想的情况是这样的，因为我们是有多台服务器进行交互，比如将iot服务器中的图片传输到另一个我们的本地服务器中进行图片处理，然后给出返回的结果，我们发现iot上面只有本地文件读写，没有我们想要的功能，所以就增加了一个向其他服务器发送文件的服务。
后来因为还使用到了一些云服务的API，感觉服务之间有些相似，就决定把这两个服务整合到一起，因为都是送往远程服务器处理然后得到返回值。
在参数的设计方面，将http和https协议的请求整合到了一起，所以第一个参数需要加上该项来判断具体的使用协议。最后一个参数是考虑到一些云服务API的使用需要验证身份。
起初我们也认为该服务的输入有些复杂，后来考虑到使用此服务的场景一般会与其他服务结合，接收上层服务传下的参数，所以就没有进行修改。

因为我们对iot也不是十分透彻，所以对服务的理解和使用可能还存在许多问题，为了提供更好的服务和用户体验，我们会积极吸取您的意见和建议并进行改正，也希望能够学到更多有用的不论是技术上还是服务结构设计上的知识。

2016-10-27 02:03 UTC, jiangzidong commented
我只是觉得作为"文件发送服务", 范围太大, 不同的server可能处理的方法, 以及对输入数据的要求, 都是不同的. 很难兼顾各种场景.
在你的实现中, 是直接将文件内容用octet-stream类型发给server. 其他第三方的server可能并不认识这样的类型, 或者需要发送端对数据做预处理, 等等.  

不如就针对特定的cloud service来封装我们的服务.

2016-10-27 02:24 UTC, helianthuswhite commented
嗯，好的，那我先把该服务改成微软的云服务。

不过我觉得在iot中，实现本地服务器的文件传输也挺重要的，因为现在的智能互联系统通常有多个硬件设备，就导致可能需要搭建不止一个服务器。这多个服务器之间想要进行文件传输该怎么处理呢？

我不知道我的想法是否正确，如果需要实现此服务，该怎么去改进？

2016-10-27 02:37 UTC, jonathanding commented
这是一个有用的需求，但是一个比较大的feature。一种可行的实现方式是需要在系统中部署一个文件转发服务（类似于现在的Message Broker），当工作流中的一个节点（假设为X）的outport标注为文件类型并且连接到另外一个节点（假设为Y）的inport（同样为文件类型）时，系统会把该文件通过文件转发服务在各个节点之间转送。

系统需要可以适配多种类型的第三方组件并利用他们完成文件转发服务（就像Message Broker可以基于mqtt或者其他协议一样）。例如一种适配是开一个FTP server。X把文件upload过去，然后把文件地址告诉Y，Y把它取下来。其他的例如开一个Redis或memcached之类的，或者使用一个云服务（例如网盘）做中转。

当然一种极端的实现是直接点对点传输，即Y可以直接从X那儿取到文件，而不需要第三方介入。

2016-10-27 17:18 UTC, helianthuswhite commented
我重新提交了微软人脸识别的服务，文件转发的服务可能一时无法解决。

2016-10-30 04:22 UTC, jiangzidong commented
请在doc中描述一下 微软人脸识别服务的链接， 返回值的结构， 以及如何训练等问题

2016-10-31 08:30 UTC, helianthuswhite commented
修改完成

2016-11-01 01:54 UTC, jiangzidong requested changes

2016-11-01 01:54 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/life/ms_face/start.js
> + service_shared.ms_face = function(filepath, key, data_handler, err_handler) {
请将start和kernel的service_shared改为shared

2016-11-01 01:54 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/life/ms_face/start.js
> +
你这里用原生的https来request, 我建议改为request module
e.g.
```
var request = require("request");
function recognize(img,key,data_handler) {
  var options = {
    uri:'https://api.projectoxford.ai/face/v1.0/detect?returnFaceId=true&returnFaceLandmarks=true&returnFaceAttributes=age,gender,headPose,smile,facialHair,glasses',
    method:'POST',
    headers: {
      'Content-Type':'application/octet-stream',
      'Content-Length': img.length,
      'Ocp-Apim-Subscription-Key':key
    },
    body:img
  };

  request(options, function(e, r1, res) {
    console.log(e); // error msg
    console.log(r1);
    console.log(res);// response body
  //process res
  });
}
```

2016-11-01 01:56 UTC, jiangzidong commented
在试用了你的新增服务后, 我建议使用request带代替原生https
主要原因是request会走系统代理, 而https module设置代理会比较麻烦

2016-11-02 10:52 UTC, helianthuswhite commented
谢谢指点，修改完成。

2016-11-02 12:44 UTC, sunpeng1996 commented
LGTM!

2016-11-03 00:36 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/life/ms_face/start.js
> +      console.log(e);
you can still use the err_hander to handle the request error

2016-11-03 01:33 UTC, helianthuswhite commented
Oh, i'm so careless. That's all right.

2016-11-03 01:48 UTC, jiangzidong approved these changes

2016-11-03 01:50 UTC, jiangzidong commented
LGTM

建议你将该服务发布, 请参照http://01org.github.io/intel-iot-services-orchestration-layer/#getstarted/example/publish_service

名字我的建议是 iotsol-service-msface

Thanks

2016-11-03 02:30 UTC, helianthuswhite commented
👌 I have done this.

2016-11-03 06:55 UTC, merged