Dev-I2c-communication
01org/intel-iot-services-orchestration-layer pull request #52
Opened 2016-10-27 17:58 UTC by 2659494286

Provide I2c communication service

2016-10-28 05:06 UTC, 2659494286 commented
我想添加这个用于提供Edison上与I2c设备通信的服务，测试时使用基于I2c通信的温湿度传感器没有问题

2016-10-30 04:34 UTC, jiangzidong requested changes

2016-10-30 04:34 UTC, jiangzidong commented on demo/edison/thing_bundle/I2c/I2c/i18n.zh-CN.json
> +  "I2c":"I2c通信",
重复

2016-10-30 04:34 UTC, jiangzidong commented on demo/edison/thing_bundle/I2c/i18n.zh-CN.json
> +  "I2c":"基于I2c协议的通信"
key名字不能一样。 该文件的意思是， 当遇到“I2c”这样的字符，应该翻译成什么中文

2016-10-30 04:34 UTC, jiangzidong commented on demo/edison/thing_bundle/I2c/I2c/start.js
> +shared.i2c = new m.I2c(8);
为什么是8？

2016-10-30 04:34 UTC, jiangzidong commented on doc/md/edison/I2c.md
> +`value`:Buffer Array
不要输出Buffer类型， 这是nodejs特有的类型。 要输出可以转化为json格式的类型， 比如number string or plain object

2016-10-30 04:34 UTC, jiangzidong commented on doc/md/edison/I2c.md
> +`signal`:number
你现在的服务有2个输入， signal和trigger
我建议trigger作为输入， signal（是不是叫做cmd更加合适）作为config

2016-10-30 04:35 UTC, jiangzidong commented
该服务其实是读i2c设备， 是否名字改为i2c-read

2016-10-30 07:20 UTC, 2659494286 commented
好的，我改改哈

2016-10-31 01:13 UTC, jiangzidong requested changes

2016-10-31 01:13 UTC, jiangzidong commented on demo/edison/thing_bundle/I2c/I2c/I2c/kernel.js
> +var value={};
value是否应该是array?

2016-10-31 01:13 UTC, jiangzidong commented on demo/edison/thing_bundle/I2c/I2c/I2c/service.json
> +          "type": "object"
value的类型, 为什么是object而不是array?

2016-10-31 01:13 UTC, jiangzidong commented on demo/edison/thing_bundle/I2c/I2c/i18n.zh-CN.json
> +  "I2c":"基于I2c协议的通信"
"基于I2c协议的通信" 名字太长了, 直接I2C即可

2016-10-31 01:13 UTC, jiangzidong commented on demo/edison/thing_bundle/I2c/I2c/thing.json
> +  "description": "I2c"
description中可以详细一些

2016-10-31 01:16 UTC, jiangzidong commented
@2659494286 , 你好, 除了上面的review以外, 还有2个建议
1) 现在的目录结构, 就是I2c/I2c/I2c...
建议改为I2C/I2C-read/xxx

2) 现在PR中有3个commit, 请最后将这些commit合并为一个

谢谢!

2016-10-31 14:26 UTC, 2659494286 commented
ok

2016-11-01 06:20 UTC, jiangzidong requested changes

2016-11-01 06:20 UTC, jiangzidong commented on demo/edison/thing_bundle/I2c/thing.json
> +  "description": "I2c-description"
description建议是 I2C-communication 或者 I2C-protocol

2016-11-01 06:20 UTC, jiangzidong commented on demo/edison/thing_bundle/I2c/I2c-read/service.json
> +  "description": "I2c-read-description",
建议改为: read byte from I2C device

2016-11-01 06:33 UTC, 2659494286 commented
ok了

2016-11-03 01:21 UTC, jiangzidong approved these changes

2016-11-03 01:24 UTC, jiangzidong commented
LGTM
同时, 建议你发布这个服务
http://01org.github.io/intel-iot-services-orchestration-layer/#getstarted/example/publish_service
名字建议是 iotsol-service-mraa-i2cread

Thanks

2016-11-03 16:37 UTC, 2659494286 commented
恩   已经发布好了

2016-11-04 03:30 UTC, merged