重新提交九轴姿态融合算法
01org/intel-iot-services-orchestration-layer pull request #57
Opened 2016-11-04 16:53 UTC by windmillknight

根据mpu9150九轴动作传感器各轴数据，计算欧拉角。
mpu9150通过i2c接口与edison 进行通信，通过intel upm库实现控制。
输入：dt:采样频率。
           K:加速度计所占权重。
           tragger:触发信号。
输出：pitch:俯仰角
           roll：翻滚角
           yaw:偏航角

该算法也是适用于其他九轴动作传感器如mpu9150，lsm9ds0等，需要修改所包含的库。

2016-11-07 01:15 UTC, jiangzidong requested changes

2016-11-07 01:15 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mpu9150/9_axis_attitude_fusion_algorithm/kernel.js
> +<<<<<<< HEAD
这些需要删掉. 请保证该版本可以正常运行

2016-11-07 01:15 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mpu9150/9_axis_attitude_fusion_algorithm/service.json
> +}
回车结尾

2016-11-07 01:15 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mpu9150/9_axis_attitude_fusion_algorithm/start.js
> +
下面的要删掉

2016-11-07 01:15 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mpu9150/9_axis_attitude_fusion_algorithm/start.js
> +shared.sensorObj = require('jsupm_mpu9150');
你是怎么在edison上安装这个库的? 直接npm install 吗

2016-11-08 03:52 UTC, windmillknight commented on center/lib/hubbundles/thingbundle/mpu9150/9_axis_attitude_fusion_algorithm/start.js
> +shared.sensorObj = require('jsupm_mpu9150');
您好，不好意思这么晚回复您，我使用的是这个https://github.com/intel-iot-devkit/upm，
通过
echo "src mraa-upm http://iotdk.intel.com/repos/3.5/intelgalactic-dev/opkg/i586" > /etc/opkg/mraa-upm.conf
opkg update
opkg install upm
指令安装。
根据官方说法，也可以直接通过npm安装，不过需要ediosn 上首先有mraa库，没有测试过。
另外如果edison使用的是edison for arduino 扩展板的i2c接口来连接mpu9150,需要将var sensorObj.MPU9150() 中最后一个参数改为false。
同时这个算法也可以支持其他的姿态传感器，如sparkfun的lsm9df0九轴传感器，只需要更换upm对象即可。

2016-11-08 04:45 UTC, jiangzidong requested changes

2016-11-08 04:45 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mpu9150/9_axis_attitude_fusion_algorithm/kernel.js
> +
这个函数的缩进请调整一下, 特别是后半部分

2016-11-08 04:45 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mpu9150/9_axis_attitude_fusion_algorithm/service.json
> +  "description": "输出欧拉角",
请用英文描述

2016-11-08 04:45 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/mpu9150/9_axis_attitude_fusion_algorithm/service.json
> +  "description": "输出欧拉角",
需要中文的请添加i18n文件

2016-11-08 04:45 UTC, jiangzidong commented on doc/md/builtin/mpu9150.md
> +`dt`: number.sample frequency.
我觉得, 是否将dt和k放入config? 这个参数是运行中可变, 或者通过前面的其他模块计算出来的吗

2016-11-08 04:45 UTC, jiangzidong commented on doc/md/builtin/mpu9150.md
> +`dt`: number.sample frequency.
能否补充一张工作流图片

2016-11-09 12:58 UTC, windmillknight commented
您好，我已经修改了内容，下面是工作流截图。
![default](https://cloud.githubusercontent.com/assets/18244752/20139059/2e52be36-a6bf-11e6-854a-89c958908938.png)

2016-11-10 00:23 UTC, jiangzidong commented
*请将图片放入md文件中
*将该服务放入demo/edison/ 下, 对应文档的地址也相应改变. 应该该服务与硬件平台相关, 并不是一个general service
* 请将所有commit合并为1个

Thanks

2016-11-10 04:04 UTC, closed without merging