add ds18b20 service
01org/intel-iot-services-orchestration-layer pull request #60
Opened 2016-11-06 15:01 UTC by LLoyou00

增加了数字温度传感器DS18B20的支持服务

2016-11-06 15:27 UTC, LLoyou00 commented
在DS18B20的实现中，我们发现由于单总线协议对于时序的苛刻要求与iot-sol这个非实时系统的矛盾，使得**数字**温度传感器的使用十分困难。

> https://github.com/intel-iot-devkit/mraa/pull/415

首先感谢这个开源项目的经验和接线方法，利用Edison开发板的串口特性与二极管的单向通路特性，可以通过焊接一个二极管完成读写的分离，从而实现在非实时系统上与单总线设备实时交互数据（也就是说其实应该对于其他单总线协议也可以用这个方法解决通讯问题）

>  同时可以参考  https://www.maximintegrated.com/en/app-notes/index.mvp/id/214

当然，经过测试，使用这种方法之后，iot-sol的启停等待时间会加长。。。

2016-11-07 01:23 UTC, jiangzidong requested changes

2016-11-07 01:23 UTC, jiangzidong commented on node_modules/hope-demo/startkit/thing_bundle/temperature/DS18B20/service.json
> +  "id": "HOPE_SERVICE_a6b85380_a422_11e6_bfa4_514dc020b9ba",
id , thing 是不需要的, 系统会自己分配

2016-11-07 01:23 UTC, jiangzidong commented on node_modules/hope-demo/startkit/thing_bundle/temperature/DS18B20/service.json
> +}
回车结尾

2016-11-07 01:23 UTC, jiangzidong commented on node_modules/hope-demo/startkit/thing_bundle/temperature/DS18B20/service.json
> +  "description": "通过串口实现Edison难以实现的单总线协议.硬件连接:https://github.com/intel-iot-devkit/mraa/pull/415",
请用英文描述, 如果需要中文, 请写额外的i18n文件

2016-11-07 01:23 UTC, jiangzidong commented on node_modules/hope-demo/startkit/thing_bundle/temperature/DS18B20/start.js
> +var sensorObj = require('jsupm_ds18b20');
直接npm install 安装这个库是吗, 需要其他的配置吗

2016-11-07 01:24 UTC, jiangzidong commented
请问"iot-sol的启停等待时间会加长", 具体是多长? 有原来和现在的对比吗

2016-11-07 01:26 UTC, jiangzidong commented
"Edison串口进行可还原的简易改装", 能否给出你们使用的原理图和实物照片. 这样方便他人重现

2016-11-07 02:13 UTC, LLoyou00 commented on node_modules/hope-demo/startkit/thing_bundle/temperature/DS18B20/start.js
> +var sensorObj = require('jsupm_ds18b20');
这个库在可以直接通过npm安装，需要先安装npm install mraa

2016-11-07 04:50 UTC, LLoyou00 commented
通过这个方案使用DS18B20这个数字式传感器时，在启动工作流是需要十秒左右的时间对串口进行初始化，以及传感器的探测。
硬件的原理图如下
![image](https://cloud.githubusercontent.com/assets/9455777/20046755/4af19ef0-a4e8-11e6-97f9-ad7eda72d4a2.png)
如果使用DFRobot提供的DS18B20模块，不需要在增加上拉电阻，只需要将TXD RXD两根针脚通过二极管连接起来(注意二极管的方向)然后将DS18B20的数据线接在RXD引脚上即可

2016-11-07 05:25 UTC, jiangzidong commented
"在启动工作流时需要十秒左右的时间对串口进行初始化，以及和传感器建立通讯。"

这个十秒是`shared.sensor = new sensorObj.DS18B20(0); `这个运行时间, 还是说系统显示工作流已经初始化好了, 但是需要人为等待10s后才能真正运行

2016-11-07 05:50 UTC, LLoyou00 commented
是shared.sensor = new sensorObj.DS18B20(0);的运行时间。
因为DS18B20这个传感器使用的是单总线协议通讯，使用这个协议有一个很大的特点就是可以在一根数据线上接上多个单总线通讯设备，每个设备有一个内置的ID用于区分。所以在初始化时须要有一个设备发现的过程。
宏观的表现就是点击启动工作流后，会有十秒左右的等待时间才会显示工作流启动成功。

2016-11-07 05:59 UTC, jiangzidong commented
请将多个commit合并为1个, 并且service的路径改为node_modules/hope-demo/edison/thing_bundle/DS18B20/temprature

在edison hub下, thing是DS18B20 service是temprature

2016-11-07 06:00 UTC, jiangzidong commented
请再补上相关文档, 说明启动时间, 你所在的硬件平台, 相关链接 等内容

2016-11-07 06:01 UTC, LLoyou00 commented on node_modules/hope-demo/startkit/thing_bundle/temperature/DS18B20/service.json
> +  "description": "通过串口实现Edison难以实现的单总线协议.硬件连接:https://github.com/intel-iot-devkit/mraa/pull/415",
修改完成

2016-11-07 06:01 UTC, LLoyou00 commented on node_modules/hope-demo/startkit/thing_bundle/temperature/DS18B20/service.json
> +  "id": "HOPE_SERVICE_a6b85380_a422_11e6_bfa4_514dc020b9ba",
修改完成

2016-11-07 06:02 UTC, LLoyou00 commented on node_modules/hope-demo/startkit/thing_bundle/temperature/DS18B20/service.json
> +}
修改完成

2016-11-07 10:50 UTC, LLoyou00 commented
![image](https://cloud.githubusercontent.com/assets/9455777/20055049/692cf662-a51a-11e6-95dc-7f58bb9382ab.png)
实验所使用的硬件
![image](https://cloud.githubusercontent.com/assets/9455777/20055066/7f4229cc-a51a-11e6-86a3-0b236ab388d4.png)
在串口引脚上接上二极管
![image](https://cloud.githubusercontent.com/assets/9455777/20055091/9340fd54-a51a-11e6-8c94-ce9fb877a3f6.png)
安装到Edison上

理论指导：https://www.maximintegrated.com/en/app-notes/index.mvp/id/214

2016-11-08 01:43 UTC, jiangzidong requested changes

2016-11-08 01:43 UTC, jiangzidong commented on node_modules/hope-demo/edison/thing_bundle/DS18B20/temprature/service.json
> +  "name": "DS18B20",
name应该是temprature

2016-11-08 01:45 UTC, jiangzidong commented
@LLoyou00 请再补上文档, 文档地址在doc/md/edison , 可以参照i2c的例子来写. 没有特别固定的格式, 只要把信息表达清楚, 方便他人使用,就可以了. Thanks

2016-11-08 05:14 UTC, LLoyou00 commented
@jiangzidong 请问文档要放在哪个路径呢？我没有找到doc/md/edison,需要我自己创建吗？

2016-11-08 05:22 UTC, jiangzidong commented
你更新一下, 应该就有了. 现在gitthub上是有的https://github.com/01org/intel-iot-services-orchestration-layer/tree/dev/doc/md/edison

2016-11-08 05:58 UTC, closed without merging