Enhance the function of http_request
01org/intel-iot-services-orchestration-layer pull request #61
Opened 2016-11-07 09:23 UTC by suxiongye

Enhance the function of http_request by add a variable string

2016-11-08 01:35 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/network/http_request/i18n.zh-CN.json
>  }
回车结尾

2016-11-08 01:35 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/network/http_request/i18n.zh-CN.json
> +  "send http request":"发送可拼接的http请求,并指定方法",
还是保留原来的翻译吧, 没有必要强调"可拼接"

2016-11-08 01:35 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/network/http_request/kernel.js
> +if (IN.trigger) {
去掉这个if判断

2016-11-08 01:35 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/network/http_request/kernel.js
> +	service_shared.http_request(CONFIG.url1, IN.url2, CONFIG.method, CONFIG.headers, CONFIG.body, CONFIG.timeout, CONFIG.proxy)
该service当时提交时, 没有将tab转化为2个空格, 能否帮忙将下面文件中的tab都转化为2个空格?谢谢

2016-11-08 01:35 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/network/http_request/kernel.js
> +if (IN.trigger) {
因为改服务的触发应该如下: 不管trigger 或者 url2 有任何输入, 马上拼接url并启动request

2016-11-08 01:41 UTC, jiangzidong commented
关于文档和图片, 有如下建议
1, 文档还需要修改md文件
2, 图片请提供2个例子:
* case1, 不用url2, 直接trigger, 就是原来的例子
* case2, 不用trigger (trigger不要预置为true), 并给出request的config配置图. trigger只是2个触发信号之一, 如果需要用url2触发, 就不需要使用trigger了

2016-11-08 04:33 UTC, suxiongye commented
@jiangzidong 请问md文件指的是？

2016-11-08 04:35 UTC, jiangzidong commented
@suxiongye 请参考https://github.com/01org/intel-iot-services-orchestration-layer/blob/dev/doc/md/builtin/network.md

2016-11-08 05:44 UTC, suxiongye commented
@jiangzidong 文档已做修改

2016-11-09 02:54 UTC, suxiongye commented
@jiangzidong 例子已加上，同时程序也改为两个条件输入

2016-11-09 02:58 UTC, jiangzidong requested changes

2016-11-09 02:58 UTC, jiangzidong commented on center/lib/hubbundles/thingbundle/network/http_request/kernel.js
> +  .then(function(response) {
缩进修改一下, 最后用回车结尾

2016-11-09 02:59 UTC, jiangzidong commented
图1有问题, trigger需要有default输入, 你可以随便填一个. 否则改服务不会触发

2016-11-09 02:59 UTC, jiangzidong commented
以上内容修改好, 就可以merge了

2016-11-09 03:21 UTC, suxiongye commented on center/lib/hubbundles/thingbundle/network/http_request/kernel.js
> +  .then(function(response) {
缩进改成tab=2space?

2016-11-09 03:36 UTC, suxiongye commented
@jiangzidong 图片已按要求修改，加上了回车，缩进改成两个空格的tab

2016-11-09 03:56 UTC, jiangzidong approved these changes

2016-11-09 03:56 UTC, jiangzidong commented
请将commit合并为1个,谢谢

2016-11-09 04:34 UTC, suxiongye commented
@jiangzidong 请问怎么合并，是重新提交一个请求么？还是用rebase？

2016-11-09 04:35 UTC, jiangzidong commented
git squash @suxiongye

2016-11-09 04:46 UTC, suxiongye commented
@jiangzidong 但是中间的有他人提交的部分

2016-11-09 04:52 UTC, suxiongye commented
@jiangzidong 我重新提交了一个，您看看

2016-11-09 04:53 UTC, closed without merging