添加数字式温度传感器DS18B20的支持服务
01org/intel-iot-services-orchestration-layer pull request #63
Opened 2016-11-08 06:09 UTC by LLoyou00

不好意思。。。之前的pull requset被误删了

2016-11-08 06:24 UTC, jiangzidong commented on doc/md/edison/DS18B20.md
> +![](./pic/i2cconfig.jpg)
图片没有上传

2016-11-08 06:44 UTC, LLoyou00 commented on doc/md/edison/DS18B20.md
> +![](./pic/i2cconfig.jpg)
已修改

2016-11-08 06:47 UTC, jiangzidong requested changes

2016-11-08 06:47 UTC, jiangzidong commented on doc/md/edison/DS18B20.md
> +`pin`:number
pin是什么? 似乎没有用到

2016-11-08 07:10 UTC, LLoyou00 commented on doc/md/edison/DS18B20.md
> +`pin`:number
写傻掉了。。。已改

2016-11-08 11:42 UTC, LLoyou00 commented
@jiangzidong 请问还有什么地方需要修改吗？如果没有的话可以merge吗？

2016-11-09 03:55 UTC, jiangzidong approved these changes

2016-11-09 03:56 UTC, merged